language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

script:
  - docker build --pull -t alvisisme/openjdk:8 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alvisisme/openjdk:8
  - echo "$ALIYUN_PASSWORD" | docker login -u "$ALIYUN_USERNAME" --password-stdin registry.cn-hangzhou.aliyuncs.com
  - docker tag alvisisme/openjdk:8 registry.cn-hangzhou.aliyuncs.com/alvisisme/openjdk:8
  - docker push registry.cn-hangzhou.aliyuncs.com/alvisisme/openjdk:8
